CREATE TABLE IF NOT EXISTS project (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(255) NOT NULL,
	created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS person (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	project_id INTEGER NOT NULL REFERENCES project (id),
	name VARCHAR(255) NOT NULL,
	color_index INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS task (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	project_id INTEGER NOT NULL REFERENCES project (id),
	person_id INTEGER REFERENCES person (id),
	title VARCHAR(255) NOT NULL,
	start_date TEXT NOT NULL,
	end_date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS memo (
	project_id INTEGER PRIMARY KEY REFERENCES project (id),
	content TEXT NOT NULL
);
